Add MSVC support

diff --git a/scripts/build.d/0-compile b/scripts/build.d/0-compile
--- a/scripts/build.d/0-compile
+++ b/scripts/build.d/0-compile
@@ -2,56 +2,41 @@
 
 ## Compile binaries and get dependencies
 
-
-# Create a dummy gcc wrapper that just calls the base compiler.
-# This is used during the configure step as we are not interested in config dependencies.
-generate_dummy_toolchain_wrapper() {
-	local file="$1"
-	local compiler="$2"
-	echo "#!/bin/bash
-$(escape_args "$compiler") \"\$@\"" > "$file"
-	chmod +x "$file"
-}
-
-# Create a gcc wrapper that records which includes and libraries are used.
-#
-# It also filters the -rdynamic flag as CMake always sneakily adds it to the linker flags
-# for Linux builds - but it's not needed if we don't use dlopen and makes the builds
-# less portable.
-# Manually add -Wl,--export-dynamic to the default CMake behaviour of it's really needed.
-generate_toolchain_wrapper() {
-	local file="$1"
-	local compiler="$2"
-	local root="$3"
-	local depsdir="$4"
-	
-	echo "#!/bin/bash
-compiler=$(escape_args "$compiler")
-root=$(escape_args "$root")
-depsdir=$(escape_args "$depsdir")
-" > "$file"
-	
-	tail -n+2 "${scriptdir}/compiler-wrapper" >> "$file"
-	
-	chmod +x "$file"
-}
-
-# Generate a CMake toolchain file
+# Generate a CMake toolchain file (wrapper)
 generate_toolchain_file() {
 	local file="$1"
 	local target="$2"
 	local root="$3"
 	local system="$4"
+	local toolchain="$5"
+	local depsdir="$6"
+	local compilerdir="$7"
+	local rootdir="$8"
 	
+	echo -n '' > $file
+	
+	if [ -z "$toolchain" ] ; then
 	echo "
-
 # name of the target operating system
-set(CMAKE_SYSTEM_NAME ${system})
-
+set(CMAKE_SYSTEM_NAME ${system})" >> "$file"
+	fi
+	
+	if [ ! -z "$target" ] ; then
+		echo "
 # compilers to use for C and C++
-set(CMAKE_C_COMPILER \"${PWD}/gcc\")
-set(CMAKE_CXX_COMPILER \"${PWD}/g++\")
-
+set(CMAKE_C_COMPILER \"${target}-gcc\")
+set(CMAKE_CXX_COMPILER \"${target}-g++\")" >> "$file"
+		type "${target}-windres" &>/dev/null \
+			&& echo "set(CMAKE_RC_COMPILER \"${target}-windres\")" >> "$file" || true
+	fi
+	
+	if [ ! -z "$toolchain" ] ; then
+		echo "
+include(\"${toolchain_files["$toolchain"]}\")" >> "$file"
+	fi
+	
+	if [ ! -z "$root" ] ; then
+		echo "
 # location of the target environment
 set(CMAKE_FIND_ROOT_PATH \"${root}\")
 # Also tell pkg-config because CMake doesn't
@@ -65,48 +50,54 @@ set(ENV{PKG_CONFIG_SYSROOT_DIR} \"${root}\")
 # programs in the host environment
 set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
 set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
-set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
-
-" > "$file"
-	type "${target}-windres" &>/dev/null && echo "
-
-set(CMAKE_RC_COMPILER \"${target}-windres\")
-
-" >> "$file" || true
+set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> "$file"
+	fi
+	
+	echo "
+set(depsdir \"$depsdir\")
+set(compilerdir \"$compilerdir\")
+set(rootdir \"$rootdir\")
+include(\"${scriptdir}/toolchain-wrapper.cmake\")" >> "$file"
 	
 }
-
 
 build() {
 	local arch="$1"
 	
-	local osarch="${pkgtype/-/_}_${arch/-/_}"
+	local osarch="${pkgtype//-/_}_${arch//-/_}"
 	
-	local target="${targets["${pkgtype}-${arch}"]}"
-	local root="${root_base}/${target}"
+	local target="${targets["${pkgtype}-${arch}"]:-}"
+	local toolchain="${toolchains["${pkgtype}-${arch}"]:-}"
+	
+	local root=''
+	[ -z "$target" ] || root="${root_base}/${target}"
 	
 	local bindir="${bindir}/${arch}"
 	
 	echo "  ${white}:: building for ${arch}${reset}" >&2
-	echo "target=${target} root=${root} bindir=${bindir}"
+	echo "target=${target:-} toolchain=${toolchain:-} root=${root:-} bindir=${bindir:-}"
 	
 	local builddir="${PWD}/build-${arch}"
 	e mkdir "$builddir"
 	pushd "$builddir"
 		
 		local depsdir="$builddir/deps"
-		mkdir -p "$depsdir"
+		[ -d "$depsdir" ] && rmdir -r "$depsdir"
 		
-		e generate_dummy_toolchain_wrapper 'gcc' "${target}-gcc"
-		e generate_dummy_toolchain_wrapper 'g++' "${target}-g++"
+		local rootdir="$builddir/root"
+		mkdir -p "$rootdir"
 		
-		e generate_toolchain_file 'toolchain.cmake' "$target" "$root" "$cmake_platform"
+		local compilerdir="$builddir/compiler"
+		mkdir -p "$compilerdir"
+		toolchain_file="$builddir/toolchain.cmake"
+		e generate_toolchain_file "$toolchain_file" \
+			"$target" "$root" "$cmake_platform" "$toolchain" "$depsdir" "$compilerdir" "$rootdir"
 		
 		# Set CMake options
 		local options=(
 			
 			--no-warn-unused-cli
-			-DCMAKE_TOOLCHAIN_FILE="toolchain.cmake"
+			-DCMAKE_TOOLCHAIN_FILE="$toolchain_file"
 			-DCMAKE_BUILD_TYPE=Release
 			
 			-DCMAKE_INSTALL_PREFIX="${outdir}"
@@ -115,6 +106,7 @@ build() {
 			-DCMAKE_INSTALL_BINDIR="${bindir}"
 			-DCMAKE_INSTALL_LIBDIR="${bindir}"
 			-DCMAKE_INSTALL_LIBEXECDIR="${bindir}/libexec"
+			-DCMAKE_INSTALL_INCLUDEDIR="${bindir}/libexec"
 			
 			"${cmake_options[@]:+${cmake_options[@]}}"
 			
@@ -125,11 +117,22 @@ build() {
 		add_cmake_option() {
 			local cmake_flag="$1"
 			local name="$2"
-			local escaped_flags="$(
-				eval escape_args \
-					"\"\${${name}[@]:+\${${name}[@]}}\"" \
-					"\"\${${name}_${osarch}[@]:+\${${name}_${osarch}[@]}}\""
-			)"
+			if [ -z "$toolchain" ] ; then
+				local escaped_flags="$(
+					eval escape_args \
+						"\"\${${name}[@]:+\${${name}[@]}}\"" \
+						"\"\${${name}_${osarch}[@]:+\${${name}_${osarch}[@]}}\""
+				)"
+			else
+				local tcshort="${toolchain%%-*}"
+				local tclong="${toolchain//-/_}"
+				local escaped_flags="$(
+					eval escape_args \
+						"\"\${${name}_${tcshort}[@]:+\${${name}_${tcshort}[@]}}\"" \
+						"\"\${${name}_${osarch}[@]:+\${${name}_${osarch}[@]}}\"" \
+						"\"\${${name}_${tclong}[@]:+\${${name}_${tclong}[@]}}\""
+				)"
+			fi
 			options+=( "${cmake_flag}=${escaped_flags}" )
 		}
 		
@@ -140,8 +143,7 @@ build() {
 		
 		VERBOSE=1 e cmake "${sourcedir}" "${options[@]}"
 		
-		e generate_toolchain_wrapper 'gcc' "${target}-gcc" "$root" "$depsdir"
-		e generate_toolchain_wrapper 'g++' "${target}-g++" "$root" "$depsdir"
+		mkdir -p "$depsdir"
 		
 		VERBOSE=1 e make -j"$(getconf _NPROCESSORS_ONLN)"
 		
@@ -149,44 +151,84 @@ build() {
 		
 	popd
 	
+	local binroots=( )
+	if [ -f "$rootdir/paths" ] ; then
+		while IFS= read -r binroot ; do
+			binroots+=( "$binroot" )
+		done < <(cat "$rootdir/paths" | sort -rV | uniq)
+	fi
+	[ -z "$root" ] || binroots+=( "$root" )
+	
+	local binarch="$arch"
+	[ -f "$rootdir/arch" ] && binarch="$(cat "$rootdir/arch")"
+	local suffixes=(
+		'' "$binarch"
+		"bin" "bin/$binarch" "lib" "lib/$binarch"
+		"usr/bin" "usr/bin/$binarch" "usr/lib" "usr/lib/$binarch"
+	)
 	
 	# Copy binaries from the crossdev tree
 	for binary in "${copy_from_tree[@]:+${copy_from_tree[@]}}" ; do
-		[ -f "${root}/${binary}" ] || die "missing ${binary} in ${root}"
-		e mkdir -p "${bindir}/libexec"
-		e cp --preserve=all "${root}/${binary}" "${bindir}/libexec/"
-		readlink -f "${root}/${binary}" >> "$depsdir/copy_from_tree"
+		local found=0
+		for binroot in "${binroots[@]:+${binroots[@]}}" ; do
+			for suffix in "${suffixes[@]}" ; do
+				local file="${binroot}/${suffix}/${binary}"
+				[ -f "$file" ] || continue
+				e mkdir -p "${bindir}/libexec"
+				e cp --preserve=all "$file" "${bindir}/libexec/"
+				readlink -f "$file" >> "$depsdir/copy_from_tree"
+				found=1
+				break
+			done
+			[ $found = 1 ] && break
+		done
+		[ $found = 1 ] || die "missing ${binary} for ${pkgtype}-${arch}"
 	done
-	
 	
 	# Get licenses for dependencies
 	local license_outdir="${outdir}/license"
 	for dependency in $(cat "$depsdir"/* | sort | uniq) ; do
 		
 		# Ignore dependencies from the build dir
+		[ "$dependency" = "$builddir" ] && continue
 		[[ "$dependency" == "$builddir"/* ]] && continue
 		
 		# Ignore dependencies from the source dir
+		[ "$dependency" = "$sourcedir" ] && continue
 		[[ "$dependency" == "$sourcedir"/* ]] && continue
+		
+		# Ignore dependencies from the build dir
+		[ -f "${bindir}/${dependency}" ] && continue
+		[ -f "${bindir}/libexec/${dependency}" ] && continue
 		
 		# Ignore dependencies from gcc
 		[[ "$dependency" == /usr/lib/gcc/* ]] && continue
 		
-		# All other dependencies should be in the build root
-		[[ "$dependency" == "$root"/* ]] || die "dependency outside root: ${dependency}"
+		local raw_dependency="$dependency"
 		
-		raw_dependency="$dependency"
-		dependency="${dependency#"$root"}"
+		# All other dependencies should be in the build root
+		if [[ "$dependency" == */* ]] ; then
+			local found=0
+			dependency="$(realpath "$dependency")"
+			for binroot in "${binroots[@]:+${binroots[@]}}" ; do
+				local realbinroot="$(realpath "$binroot")"
+				[[ "$dependency" == "$realbinroot"/* ]] || continue
+				dependency="${dependency#"$realbinroot"}"
+				found=1
+			done
+			[ $found = 1 ] || die "dependency outside root: ${dependency}"
+		fi
 		
 		local license_found=0
 		local license=''
 		for pattern in "${!licenses[@]}" ; do
-			if [[ "$dependency" == $pattern ]] ; then
+			if [[ "$dependency" == $pattern ]] || [[ "$raw_dependency" == $pattern ]] ; then
 				license_found=1
 				license="${licenses["$pattern"]}"
 				break
 			fi
 		done
+		
 		if [ $license_found = 0 ] ; then
 			
 			# Ignore system stuff
@@ -196,8 +238,8 @@ build() {
 			
 			match_in_array "$package" "${system_packages[@]:+${system_packages[@]}}" && continue
 			
-			[ "$package" = '' ] || die "no license for dependency: ${dependency} (${package})"
-			die "no license for dependency: ${dependency}"
+			[ "$package" = '' ] || die "no license for dependency: ${raw_dependency} = ${dependency} (${package})"
+			die "no license for dependency: ${raw_dependency} = ${dependency}"
 			
 		fi
 		[ "$license" = '' ] && continue
diff --git a/scripts/build.d/1-libs b/scripts/build.d/1-libs
--- a/scripts/build.d/1-libs
+++ b/scripts/build.d/1-libs
@@ -4,20 +4,38 @@
 
 echo "  ${white}:: getting dependencies${reset}" >&2
 
+has_library() {
+	local bindir="$1"
+	local lib="$2"
+	[ -d "$bindir" ] || return $false
+	if [ "$case_insensitive_fs" = 1 ] ; then
+		local candidate="$(
+			find "${bindir}" -mindepth 1 -maxdepth 1 -type f -iname "$lib" || true
+		)"
+		[ ! -z "$candidate" ] && [ -f "$candidate" ] && return $true
+		if [ -d "${bindir}/libexec" ] ; then
+			local candidate="$(
+				find "${bindir}/libexec" -mindepth 1 -maxdepth 1 -type f -iname "$lib" || true
+			)"
+			[ ! -z "$candidate" ] && [ -f "$candidate" ] && return $true
+		fi
+	else
+		[ -f "${bindir}/${lib}" ] && return $true
+		[ -f "${bindir}/libexec/${lib}" ] && return $true
+	fi
+	return $false
+}
 
 do_copy_binary() {
 	local f="$1"
-	local target="$2"
+	local dest="$2"
 	
 	# Prefer our own binaries/libs
-	[ -e "${bindir}/${f}" ] && return
-	[ -e "${target}/${f}" ] && return
-	[ -e "${bindir}/libexec/${f}" ] && return
-	[ -e "${target}/libexec/${f}" ] && return
+	has_library "$bindir" "$f" && return
+	has_library "$dest" "$f" && return
 	
-	e mkdir -p "${target}/libexec"
-	e cp -a "${binary}" "${target}/libexec/"
-	
+	e mkdir -p "${dest}/libexec"
+	e cp -a "$f" "${dest}/libexec/"
 }
 
 do_inherit_project() {
@@ -71,21 +89,18 @@ do_inherit_project() {
 	
 }
 
-
-# find_libraries <target> <bindir> <binary>
+# find_libraries <bindir> <binary>
 find_libraries() {
 	
-	local target="$1"
-	local root="${root_base}/${target}"
-	local bindir="$2"
-	local binary="$3"
+	local bindir="$1"
+	local binary="$2"
 	local binname="${binary##*/}"
 	
-	[ -x "$(which "${target}-objdump")" ] || die "missing ${target}-objdump"
+	[ -x "$(which objdump)" ] || die "missing objdump"
 	
 	# Get all libraries required by the binary
 	local all_libraries=(
-		$("${target}-objdump" -p "$binary" \
+		$(objdump -p "$binary" \
 			| grep -P "$objdump_lib_pattern" | sed 's/.* //' | sort | uniq)
 	)
 	echo "${binname}: all libs: ${all_libraries[*]:+${all_libraries[*]}}"
@@ -94,11 +109,12 @@ find_libraries() {
 	local libraries=( )
 	for lib in "${all_libraries[@]:+${all_libraries[@]}}" ; do
 		
-		[ "$case_insensitive_fs" = 1 ] && lib="$(echo "$lib" | tolower)"
+		llib="$lib"
+		[ "$case_insensitive_fs" = 1 ] && llib="$(echo "$lib" | tolower)"
 		
-		match_in_array "$lib" "${system_libraries[@]:+${system_libraries[@]}}" && continue
+		match_in_array "$llib" "${system_libraries[@]:+${system_libraries[@]}}" && continue
 		
-		match_in_array "$lib" "${forbidden_libraries[@]:+${forbidden_libraries[@]}}" \
+		match_in_array "$llib" "${forbidden_libraries[@]:+${forbidden_libraries[@]}}" \
 			&& die "${binname} links to blacklisted library ${lib}"
 		
 		libraries+=( "$lib" )
@@ -118,22 +134,32 @@ find_libraries() {
 	for lib in "${libraries[@]:+${libraries[@]}}" ; do
 		
 		# Don't get the library again if we already have it
-		[ -f "${bindir}/${lib}" ] && continue
-		[ -f "${bindir}/libexec/${lib}" ] && continue
+		has_library "$bindir" "$lib" && continue
 		
 		# Find the required library file
-		local name='name'
-		[ "$case_insensitive_fs" = 1 ] && name='iname'
 		local file=''
-		[ -z "$file" ] && [ -f "${root}/lib/${lib}" ] && file="${root}/lib/${lib}"
-		[ -z "$file" ] && [ -f "${root}/usr/lib/${lib}" ] && file="${root}/usr/lib/${lib}"
-		[ -z "$file" ] && [ -f "${root}/bin/${lib}" ] && file="${root}/bin/${lib}"
-		[ -z "$file" ] && [ -f "${root}/usr/bin/${lib}" ] && file="${root}/usr/bin/${lib}"
-		if [ -z "$file" ] ; then
+		for binroot in "${binroots[@]:+${binroots[@]}}" ; do
+			for suffix in "${suffixes[@]}" ; do
+				[ -d "${binroot}/${suffix}" ] || continue
+				if [ "$case_insensitive_fs" = 1 ] ; then
+					local candidate="$(
+						find "${binroot}/${suffix}" -mindepth 1 -maxdepth 1 -type f -iname "$lib" || true
+					)"
+				else
+					local candidate="${binroot}/${suffix}/${lib}"
+				fi
+				[ -z "$candidate" ] && continue
+				[ -f "$candidate" ] || continue
+				file="$candidate"
+				break
+			done
+			[ -z "$file" ] || break
+		done
+		if [ -z "$file" ] && [ -z "$toolchain" ] ; then
 			local candidate="$("${target}-g++" -print-file-name="$lib")"
 			[ -f "$candidate" ] && file="$candidate"
 		fi
-		[ -z "$file" ] && die "could not find ${lib} in ${root}"
+		[ -z "$file" ] && die "could not find ${lib} (required by ${binname})"
 		echo "${lib}: using ${file}"
 		
 		# Resolve symlinks
@@ -143,8 +169,7 @@ find_libraries() {
 			if [ ! "$targetlib" = "$lib" ] ; then
 				e ln -sT "$targetlib" "${bindir}/${lib}"
 				lib="$targetlib"
-				[ -f "${bindir}/${lib}" ] && continue
-				[ -f "${bindir}/libexec/${lib}" ] && continue
+				has_library "$bindir" "$lib" && continue
 			fi
 			[ -f "$link_target" ] || die "bad symlink: ${file} -> ${link_target}"
 			file="$link_target"
@@ -154,10 +179,10 @@ find_libraries() {
 		[[ "$(file -i "$file")" == *:\ text/* ]] && die "$file is a linker script"
 		
 		# Copy the library in our target directory
-		e cp -a "$file" "${bindir}/${lib}"
+		e cp -a "$file" "${bindir}/"
 		
 		# Recursively get the library's dependencies
-		e find_libraries "$target" "$bindir" "${bindir}/${lib}"
+		e find_libraries "$bindir" "$file"
 		
 	done
 }
@@ -165,7 +190,7 @@ find_libraries() {
 
 get_max_symbol_versions() {
 	local symvers=($(
-		"${target}-objdump" -p "$1" \
+		objdump -p "$1" \
 			| tolower \
 			| sed -n '/version references:/,$p' \
 			| tail -n+2 \
@@ -188,23 +213,51 @@ get_max_symbol_versions() {
 check_dependencies() {
 	local arch="$1"
 	
-	local target="${targets["${pkgtype}-${arch}"]}"
-	local root="${root_base}/${target}"
+	local target="${targets["${pkgtype}-${arch}"]:-}"
+	local toolchain="${toolchains["${pkgtype}-${arch}"]:-}"
+	
+	local root=''
+	[ -z "$target" ] || root="${root_base}/${target}"
 	
 	local scriptbindir="$bindir"
 	local bindir="${bindir}/${arch}"
 	
+	local builddir="${PWD}/build-${arch}"
+	local rootdir="$builddir/root"
+	
+	local binroots=( )
+	if [ -f "$rootdir/paths" ] ; then
+		while IFS= read -r binroot ; do
+			binroots+=( "$binroot" )
+		done < <(cat "$rootdir/paths" | sort -rV | uniq)
+	fi
+	[ -z "$root" ] || binroots+=( "$root" )
+	
+	local binarch="$arch"
+	[ -f "$rootdir/arch" ] && binarch="$(cat "$rootdir/arch")"
+	local suffixes=(
+		'' "$binarch"
+		"bin" "bin/$binarch" "lib" "lib/$binarch"
+		"usr/bin" "usr/bin/$binarch" "usr/lib" "usr/lib/$binarch"
+	)
+	
 	# Get required libraries
 	for binary in "${bindir}"/*  "${bindir}"/libexec/* ; do
 		[ -f "$binary" ] || continue
-		e find_libraries "$target" "$bindir" "$binary"
+		[[ "$binary" == *.lib ]] && continue
+		[[ "$binary" == *.h ]] && continue
+		e find_libraries "$bindir" "$binary"
 	done
 	
 	# Remove debugging symbols to save disk space
-	for binary in "${bindir}"/* "${bindir}"/libexec/* ; do
-		[ -f "$binary" ] || continue
-		[ -L "${binary}" ] || e "${target}-strip" "${binary}"
-	done
+	if [ ! -z "$target" ] ; then
+		for binary in "${bindir}"/* "${bindir}"/libexec/* ; do
+			[ -f "$binary" ] || continue
+			[[ "$binary" == *.lib ]] && continue
+			[[ "$binary" == *.h ]] && continue
+			[ -L "${binary}" ] || e "${target}-strip" "${binary}"
+		done
+	fi
 	
 	# Sanity check: did we build all required libraries
 	for binary in "${required_binaries[@]}" ; do
@@ -219,6 +272,8 @@ check_dependencies() {
 	declare -A required_symbol_versions
 	for binary in "${bindir}"/* "${bindir}"/libexec/* ; do
 		[ -f "$binary" ] || continue
+		[[ "$binary" == *.lib ]] && continue
+		[[ "$binary" == *.h ]] && continue
 		[ -L "${binary}" ] || e get_max_symbol_versions "${binary}"
 	done
 	
